"""initial migration

Revision ID: d694d17791a9
Revises: e4df368b2950
Create Date: 2026-10-08 18:45:11.611956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd694d17791a9'
down_revision: Union[str, Sequence[str], None] = 'e4df368b2950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_reports')
    op.add_column('research_sessions', sa.Column('report_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_sessions', 'report_content')
    op.create_table('research_reports',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('research_session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.id'], name=op.f('research_reports_research_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('research_reports_pkey'))
    )
    # ### end Alembic commands ###
